### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by librafrog** [Multarix/CharacterTracker#8]
When I do so I'm getting error code SQL001. I've tried Windows libraries and the Desktop with no luck.

**Comment by Multarix** [comment]
SQL001 means that there was an error creating the DB schema (boy am I glad I added these error codes)
As it turns out, it appears I forgot to add a `"`  somewhere. I will get this patched asap!

**Comment by Multarix** [comment]
@librafrog Ok, you should be able to save now! You'll need to re-download the .exe file, but it should work as intended. Let me know if you encounter other issues (bare in mind that the program itself is probably missing some stuff, but whats there SHOULD work haha)

**Comment by librafrog** [comment]
Yep, that fix it. @Multarix  Just letting you know that now the menu Exit button isn't working, Only <kbd>X</kbd> button closes the interface.

- [ ] When file is already created/opened it doesn't save. You have to do `Save as`
- [x] Some combination of Title and Gender gets wiped. If I set Title 1<sup>st</sup> then Gender » Title clears itself.[^1]
- [ ] Can't create `New` file if S/THING is opened or already written
---
[^1]: Is this intentional

**Comment by Multarix** [comment]
I believe the title being cleared after you set gender was intentional on my behalf. (eg, setting someone as queen, then changing them to male, would be "invalid" as they should now be a king) There were some issues related to making it auto swap if I remember correctly.

The other issues I'll have to look into at some point.
